//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sample.EnviarPDF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EnviarPDF.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Generating message contract since element name barcode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InserirBarcode", ReplyAction="*")]
        Sample.EnviarPDF.InserirBarcodeResponse InserirBarcode(Sample.EnviarPDF.InserirBarcodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InserirBarcode", ReplyAction="*")]
        System.Threading.Tasks.Task<Sample.EnviarPDF.InserirBarcodeResponse> InserirBarcodeAsync(Sample.EnviarPDF.InserirBarcodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AnexarDocumentoImportacao", ReplyAction="*")]
        void AnexarDocumentoImportacao(decimal anexoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AnexarDocumentoImportacao", ReplyAction="*")]
        System.Threading.Tasks.Task AnexarDocumentoImportacaoAsync(decimal anexoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExcluirAnexoDocumentoImportacao", ReplyAction="*")]
        void ExcluirAnexoDocumentoImportacao(decimal anexoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExcluirAnexoDocumentoImportacao", ReplyAction="*")]
        System.Threading.Tasks.Task ExcluirAnexoDocumentoImportacaoAsync(decimal anexoId);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InserirBarcodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InserirBarcode", Namespace="http://tempuri.org/", Order=0)]
        public Sample.EnviarPDF.InserirBarcodeRequestBody Body;
        
        public InserirBarcodeRequest() {
        }
        
        public InserirBarcodeRequest(Sample.EnviarPDF.InserirBarcodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InserirBarcodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string barcode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string criadoPor;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int paginas;
        
        public InserirBarcodeRequestBody() {
        }
        
        public InserirBarcodeRequestBody(string barcode, string criadoPor, int paginas) {
            this.barcode = barcode;
            this.criadoPor = criadoPor;
            this.paginas = paginas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InserirBarcodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InserirBarcodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public Sample.EnviarPDF.InserirBarcodeResponseBody Body;
        
        public InserirBarcodeResponse() {
        }
        
        public InserirBarcodeResponse(Sample.EnviarPDF.InserirBarcodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InserirBarcodeResponseBody {
        
        public InserirBarcodeResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : Sample.EnviarPDF.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<Sample.EnviarPDF.Service1Soap>, Sample.EnviarPDF.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sample.EnviarPDF.InserirBarcodeResponse Sample.EnviarPDF.Service1Soap.InserirBarcode(Sample.EnviarPDF.InserirBarcodeRequest request) {
            return base.Channel.InserirBarcode(request);
        }
        
        public void InserirBarcode(string barcode, string criadoPor, int paginas) {
            Sample.EnviarPDF.InserirBarcodeRequest inValue = new Sample.EnviarPDF.InserirBarcodeRequest();
            inValue.Body = new Sample.EnviarPDF.InserirBarcodeRequestBody();
            inValue.Body.barcode = barcode;
            inValue.Body.criadoPor = criadoPor;
            inValue.Body.paginas = paginas;
            Sample.EnviarPDF.InserirBarcodeResponse retVal = ((Sample.EnviarPDF.Service1Soap)(this)).InserirBarcode(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Sample.EnviarPDF.InserirBarcodeResponse> Sample.EnviarPDF.Service1Soap.InserirBarcodeAsync(Sample.EnviarPDF.InserirBarcodeRequest request) {
            return base.Channel.InserirBarcodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Sample.EnviarPDF.InserirBarcodeResponse> InserirBarcodeAsync(string barcode, string criadoPor, int paginas) {
            Sample.EnviarPDF.InserirBarcodeRequest inValue = new Sample.EnviarPDF.InserirBarcodeRequest();
            inValue.Body = new Sample.EnviarPDF.InserirBarcodeRequestBody();
            inValue.Body.barcode = barcode;
            inValue.Body.criadoPor = criadoPor;
            inValue.Body.paginas = paginas;
            return ((Sample.EnviarPDF.Service1Soap)(this)).InserirBarcodeAsync(inValue);
        }
        
        public void AnexarDocumentoImportacao(decimal anexoId) {
            base.Channel.AnexarDocumentoImportacao(anexoId);
        }
        
        public System.Threading.Tasks.Task AnexarDocumentoImportacaoAsync(decimal anexoId) {
            return base.Channel.AnexarDocumentoImportacaoAsync(anexoId);
        }
        
        public void ExcluirAnexoDocumentoImportacao(decimal anexoId) {
            base.Channel.ExcluirAnexoDocumentoImportacao(anexoId);
        }
        
        public System.Threading.Tasks.Task ExcluirAnexoDocumentoImportacaoAsync(decimal anexoId) {
            return base.Channel.ExcluirAnexoDocumentoImportacaoAsync(anexoId);
        }
    }
}
