//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
namespace consultaReinfPreWSDL
{
    using System;
    using System.ComponentModel;
    using System.Diagnostics;
    using System.Web.Services;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;

    // 
    // This source code was auto-generated by wsdl, Version=4.6.1055.0.
    // 


    /// <remarks/>
    // CODEGEN: O elemento de extensão WSDL opcional 'PolicyReference' do espaço para nome 'http://schemas.xmlsoap.org/ws/2004/09/policy' não foi tratado.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "BasicHttpBinding_ConsultasReinf", Namespace = "http://sped.fazenda.gov.br/")]
    public partial class ConsultasReinf : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback ConsultaInformacoesConsolidadasOperationCompleted;

        /// <remarks/>
        public ConsultasReinf()
        {
            this.Url = "https://preprodefdreinf.receita.fazenda.gov.br/WsREINF/ConsultasREINF.svc";//"https://hom-reinf.receita.fazenda.gov.br/WsREINF/ConsultasReinf.svc";
        }

        /// <remarks/>
        public event ConsultaInformacoesConsolidadasCompletedEventHandler ConsultaInformacoesConsolidadasCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sped.fazenda.gov.br/ConsultasReinf/ConsultaInformacoesConsolidadas", RequestNamespace = "http://sped.fazenda.gov.br/", ResponseNamespace = "http://sped.fazenda.gov.br/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ConsultaInformacoesConsolidadas(byte tipoInscricaoContribuinte, string numeroInscricaoContribuinte, string numeroReciboFechamento)
        {
            object[] results = this.Invoke("ConsultaInformacoesConsolidadas", new object[] {
                    tipoInscricaoContribuinte,
                    numeroInscricaoContribuinte,
                    numeroReciboFechamento});
            return ((System.Xml.XmlNode)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginConsultaInformacoesConsolidadas(byte tipoInscricaoContribuinte, string numeroInscricaoContribuinte, string numeroReciboFechamento, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ConsultaInformacoesConsolidadas", new object[] {
                    tipoInscricaoContribuinte,
                    numeroInscricaoContribuinte,
                    numeroReciboFechamento}, callback, asyncState);
        }

        /// <remarks/>
        public System.Xml.XmlNode EndConsultaInformacoesConsolidadas(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Xml.XmlNode)(results[0]));
        }

        /// <remarks/>
        public void ConsultaInformacoesConsolidadasAsync(byte tipoInscricaoContribuinte, string numeroInscricaoContribuinte, string numeroReciboFechamento)
        {
            this.ConsultaInformacoesConsolidadasAsync(tipoInscricaoContribuinte, numeroInscricaoContribuinte, numeroReciboFechamento, null);
        }

        /// <remarks/>
        public void ConsultaInformacoesConsolidadasAsync(byte tipoInscricaoContribuinte, string numeroInscricaoContribuinte, string numeroReciboFechamento, object userState)
        {
            if ((this.ConsultaInformacoesConsolidadasOperationCompleted == null))
            {
                this.ConsultaInformacoesConsolidadasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaInformacoesConsolidadasOperationCompleted);
            }
            this.InvokeAsync("ConsultaInformacoesConsolidadas", new object[] {
                    tipoInscricaoContribuinte,
                    numeroInscricaoContribuinte,
                    numeroReciboFechamento}, this.ConsultaInformacoesConsolidadasOperationCompleted, userState);
        }

        private void OnConsultaInformacoesConsolidadasOperationCompleted(object arg)
        {
            if ((this.ConsultaInformacoesConsolidadasCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaInformacoesConsolidadasCompleted(this, new ConsultaInformacoesConsolidadasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void ConsultaInformacoesConsolidadasCompletedEventHandler(object sender, ConsultaInformacoesConsolidadasCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaInformacoesConsolidadasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ConsultaInformacoesConsolidadasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Xml.XmlNode Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
}